### PR TITLE
Mark vacation properly when overlap with holidays

### LINKED ISSUE #32: Vacations are not visible on Dashboard or are shown in a wrong manner
Vacation visualization in `Vacations Time Table` panel, on Dashboard page, fails to show vacations properly.
For example, vacation for two days may be shown or may be not.
And it seems that vacation for one day is not shown at all.

### PR DESCRIPTION
**Pull request by eleidan**
Fixes #32

Add App.Helpers.isHoliday helper

### CODE REVIEW

File: app/assets/javascripts/helpers/date.js [hunk 1]
```diff
@@ -51,6 +51,20 @@ App.Helpers.isWeekend = function(date) {
   return result;
 };
 
+// TODO
```
Comment (alazarchuk) [inline app/assets/javascripts/helpers/date.js]: TO DO what?
