### PR TITLE
Fix BB Pending Approvals Rendering

### LINKED ISSUE #64: Pending Approval Requests trys to show table when there is no approval requests
The UI layout is rendered as follows:
screenshot from 2015-11-06 16 32 37

The following error appears in JS console:
```
TypeError: this.availableVacations.findWhere(...) is undefined
```

### PR DESCRIPTION
**Pull request by eleidan**
Fixes #64
Remove jquery.loadmask from assets

### CODE REVIEW

File: app/assets/javascripts/routers/router.js [hunk 1]
```diff
@@ -21,13 +21,13 @@ App.Router = Backbone.Router.extend({
 
     holidays.fetch()
       .then(function() {
```
Comment (alazarchuk) [inline app/assets/javascripts/routers/router.js]: Can you try:
```JavaScript
holidays.fetch().then(teams.fetch).then(availableVacations.fetch).then(approvalRequests.fetch)
```

Comment (eleidan) [inline app/assets/javascripts/routers/router.js]: It doesn't work.
